[package]
name = "Matching_Engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "matching_engine"
path = "src/lib.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"

[profile.release]
lto = "fat"           # 开启链接时全局优化
codegen-units = 1     # 牺牲编译速度换取运行速度
panic = "abort"       # 发生错误直接退出，不展开栈
