[package]
name = "Matching_Engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "matching_engine"
path = "src/lib.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"

[profile.release]
lto = "fat"       # Enable whole-program link-time optimization.
codegen-units = 1 # Maximize optimization opportunities across Rust code.
panic = "abort"   # Avoid stack-unwinding machinery in release builds.
